### ISSUE TITLE
Piped instance does not work

### ISSUE THREAD

**Issue by lhindir** [moom0o/uptime#178]
Hi @moom0o,

I couldn’t find an email or Matrix address, so I’m just opening an issue here. Your Piped instance responds to requests, but appears to be unable to fetch anything from YouTube. This has been the case for a few months. Would you consider taking it down if you don’t intend to fix it?

Thanks for publicly hosting your services!

**Comment by moom0o** [comment]
@lhindir it seems to work atleast for now
